### PR TITLE
Add aarch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Added aarch64 wheel build support.
Related to https://github.com/fastobo/fastobo-py/issues/245, @althonos Could you please review this PR?

### CODE REVIEW

**Comment by althonos** [comment]
@odidev : I allowed you to run the GH actions, you should be able to test your changes now.

**Comment by odidev** [comment]
I’m facing the following Assertion Error on running tests.

```
FAIL: load_graph (fastobo) 
Doctest: fastobo.load_graph 
---------------------------------------------------------------------- 
Traceback (most recent call last): 
  File "/opt/python/cp37-cp37m/lib/python3.7/doctest.py", line 2204, in runTest 
    raise self.failureException(self.format_failure(new.getvalue())) 
AssertionError: Failed doctest test for fastobo.load_graph 
  File "/ws/fastobo.cpython-37m-aarch64-linux-gnu.so", line unknown line number, in load_graph 

---------------------------------------------------------------------- 
File "/ws/fastobo.cpython-37m-aarch64-linux-gnu.so", line ?, in fastobo.load_graph 
Failed example: 
    doc[0] 
Expected:
    TermFrame(PrefixedIdent('BFO', '0000002')) 
Got: 
    TermFrame(PrefixedIdent('BFO', '0000001')) 

---------------------------------------------------------------------- 

Ran 125 tests in 10.934s

FAILED (failures=1, expected failures=3)
```
Also this error is seen in x86. Is it an expected error? Could you please have a look?

**Comment by althonos** [comment]
@odidev : this was an issue with one of the doctests failing, I have pushed a fix to the main branch, you can pull from that and it should fix it.

**Comment by odidev** [comment]
Done.

**Comment by althonos** [comment]
Thanks a bunch! I'll be making a new postrelease to get the wheels on PyPI.

**Pull request merged**
